//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<YL_APP_VERSION> YL_APP_VERSION { get; set; }
        public DbSet<YL_BBS> YL_BBS { get; set; }
        public DbSet<YL_BULLETIN> YL_BULLETIN { get; set; }
        public DbSet<YL_BULLETIN_LOG> YL_BULLETIN_LOG { get; set; }
        public DbSet<YL_BULLETIN_REVIEW> YL_BULLETIN_REVIEW { get; set; }
        public DbSet<YL_BULLETIN_TYPE> YL_BULLETIN_TYPE { get; set; }
        public DbSet<YL_CAR> YL_CAR { get; set; }
        public DbSet<YL_CLIENT> YL_CLIENT { get; set; }
        public DbSet<YL_CONFIG> YL_CONFIG { get; set; }
        public DbSet<YL_COSTLIST> YL_COSTLIST { get; set; }
        public DbSet<YL_DATASOURCE> YL_DATASOURCE { get; set; }
        public DbSet<YL_DATASOURCE_FILED> YL_DATASOURCE_FILED { get; set; }
        public DbSet<YL_DATASOURCE_IMPORT> YL_DATASOURCE_IMPORT { get; set; }
        public DbSet<YL_DATASOURCE_WHERE> YL_DATASOURCE_WHERE { get; set; }
        public DbSet<YL_DATAUP> YL_DATAUP { get; set; }
        public DbSet<YL_DATAUP_FILED> YL_DATAUP_FILED { get; set; }
        public DbSet<YL_DB_SERVER> YL_DB_SERVER { get; set; }
        public DbSet<YL_DB_SERVER_TYPE> YL_DB_SERVER_TYPE { get; set; }
        public DbSet<YL_DISTRICT> YL_DISTRICT { get; set; }
        public DbSet<YL_DISTRICT_REGION> YL_DISTRICT_REGION { get; set; }
        public DbSet<YL_EXPORT_LOG> YL_EXPORT_LOG { get; set; }
        public DbSet<YL_FILES> YL_FILES { get; set; }
        public DbSet<YL_FLOW> YL_FLOW { get; set; }
        public DbSet<YL_FLOW_FLOWNODE> YL_FLOW_FLOWNODE { get; set; }
        public DbSet<YL_FLOW_FLOWNODE_FLOW> YL_FLOW_FLOWNODE_FLOW { get; set; }
        public DbSet<YL_FUNCTION> YL_FUNCTION { get; set; }
        public DbSet<YL_GARAGE> YL_GARAGE { get; set; }
        public DbSet<YL_INSURER> YL_INSURER { get; set; }
        public DbSet<YL_INSURER_PRODUCT> YL_INSURER_PRODUCT { get; set; }
        public DbSet<YL_LOG> YL_LOG { get; set; }
        public DbSet<YL_LOGIN> YL_LOGIN { get; set; }
        public DbSet<YL_LOGIN_HISTORY> YL_LOGIN_HISTORY { get; set; }
        public DbSet<YL_MESSAGE> YL_MESSAGE { get; set; }
        public DbSet<YL_MESSAGE_TYPE> YL_MESSAGE_TYPE { get; set; }
        public DbSet<YL_MODULE> YL_MODULE { get; set; }
        public DbSet<YL_OAUTH> YL_OAUTH { get; set; }
        public DbSet<YL_ORDER> YL_ORDER { get; set; }
        public DbSet<YL_ORDER_FLOW> YL_ORDER_FLOW { get; set; }
        public DbSet<YL_ORDER_INSURE> YL_ORDER_INSURE { get; set; }
        public DbSet<YL_ORDER_INSURE_PRODUCT> YL_ORDER_INSURE_PRODUCT { get; set; }
        public DbSet<YL_ORDER_RESCUE> YL_ORDER_RESCUE { get; set; }
        public DbSet<YL_ORDER_RESCUE_SEND> YL_ORDER_RESCUE_SEND { get; set; }
        public DbSet<YL_QUERY> YL_QUERY { get; set; }
        public DbSet<YL_QUESTION> YL_QUESTION { get; set; }
        public DbSet<YL_QUESTION_TYPE> YL_QUESTION_TYPE { get; set; }
        public DbSet<YL_ROLE> YL_ROLE { get; set; }
        public DbSet<YL_ROLE_CONFIG> YL_ROLE_CONFIG { get; set; }
        public DbSet<YL_ROLE_QUERY_AUTHORITY> YL_ROLE_QUERY_AUTHORITY { get; set; }
        public DbSet<YL_SALESMAN> YL_SALESMAN { get; set; }
        public DbSet<YL_SCRIPT> YL_SCRIPT { get; set; }
        public DbSet<YL_SCRIPT_GROUP_LIST> YL_SCRIPT_GROUP_LIST { get; set; }
        public DbSet<YL_SCRIPT_TASK> YL_SCRIPT_TASK { get; set; }
        public DbSet<YL_SCRIPT_TASK_LOG> YL_SCRIPT_TASK_LOG { get; set; }
        public DbSet<YL_SMS_SEND> YL_SMS_SEND { get; set; }
        public DbSet<YL_TASK> YL_TASK { get; set; }
        public DbSet<YL_TASK_FLOW> YL_TASK_FLOW { get; set; }
        public DbSet<YL_TASK_FLOW_HANDLE> YL_TASK_FLOW_HANDLE { get; set; }
        public DbSet<YL_TASK_FLOW_HANDLE_USER> YL_TASK_FLOW_HANDLE_USER { get; set; }
        public DbSet<YL_TEAM> YL_TEAM { get; set; }
        public DbSet<YL_USER> YL_USER { get; set; }
        public DbSet<YL_USER_ADDRESS> YL_USER_ADDRESS { get; set; }
        public DbSet<YL_USER_CARD> YL_USER_CARD { get; set; }
        public DbSet<YL_USER_MESSAGE> YL_USER_MESSAGE { get; set; }
        public DbSet<YL_USER_WALLET> YL_USER_WALLET { get; set; }
        public DbSet<YL_USER_WITHDRAW> YL_USER_WITHDRAW { get; set; }
        public DbSet<YL_WEIXIN_USER> YL_WEIXIN_USER { get; set; }
    }
}
