//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_BBS
    {
        public YL_BBS()
        {
            this.YL_BBS1 = new HashSet<YL_BBS>();
            this.YL_FILES = new HashSet<YL_FILES>();
            this.YL_USER1 = new HashSet<YL_USER>();
        }
    
        public int ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public int MESSAGE_TYPE_ID { get; set; }
        public Nullable<int> DISTRICT_ID { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public string NAME { get; set; }
        public string CONTENT { get; set; }
        public System.DateTime ADD_TIME { get; set; }
        public string STATUS { get; set; }
        public System.DateTime STATUS_TIME { get; set; }
        public int STAR_NUM { get; set; }
        public string TYPE { get; set; }
    
        public virtual YL_DISTRICT YL_DISTRICT { get; set; }
        public virtual ICollection<YL_BBS> YL_BBS1 { get; set; }
        public virtual YL_BBS YL_BBS2 { get; set; }
        public virtual YL_USER YL_USER { get; set; }
        public virtual YL_MESSAGE_TYPE YL_MESSAGE_TYPE { get; set; }
        public virtual ICollection<YL_FILES> YL_FILES { get; set; }
        public virtual ICollection<YL_USER> YL_USER1 { get; set; }
    }
}
