//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_BULLETIN
    {
        public YL_BULLETIN()
        {
            this.YL_BULLETIN_LOG = new HashSet<YL_BULLETIN_LOG>();
            this.YL_BULLETIN_REVIEW = new HashSet<YL_BULLETIN_REVIEW>();
            this.YL_FILES = new HashSet<YL_FILES>();
            this.YL_ROLE = new HashSet<YL_ROLE>();
        }
    
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string PIC { get; set; }
        public string TYPE_CODE { get; set; }
        public string CONTENT { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string PUBLISHER { get; set; }
        public System.DateTime ISSUE_DATE { get; set; }
        public short IS_SHOW { get; set; }
        public short IS_IMPORT { get; set; }
        public short IS_URGENT { get; set; }
        public short AUTO_PEN { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public System.DateTime UPDATE_TIME { get; set; }
        public string REGION { get; set; }
    
        public virtual ICollection<YL_BULLETIN_LOG> YL_BULLETIN_LOG { get; set; }
        public virtual ICollection<YL_BULLETIN_REVIEW> YL_BULLETIN_REVIEW { get; set; }
        public virtual ICollection<YL_FILES> YL_FILES { get; set; }
        public virtual ICollection<YL_ROLE> YL_ROLE { get; set; }
    }
}
