//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_COSTLIST
    {
        public int ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string ORDER_NO { get; set; }
        public Nullable<decimal> COST { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> STATUS_TIME { get; set; }
        public string TYPE { get; set; }
    
        public virtual YL_USER YL_USER { get; set; }
    }
}
