//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_CONFIG
    {
        public int ID { get; set; }
        public string TYPE { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string VALUE { get; set; }
        public string REMARK { get; set; }
        public string REGION { get; set; }
        public Nullable<int> ADD_USER_ID { get; set; }
        public Nullable<System.DateTime> ADD_TIEM { get; set; }
    }
}
