//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_DATASOURCE
    {
        public YL_DATASOURCE()
        {
            this.YL_DATASOURCE_FILED = new HashSet<YL_DATASOURCE_FILED>();
            this.YL_DATASOURCE_WHERE = new HashSet<YL_DATASOURCE_WHERE>();
            this.YL_DATASOURCE_IMPORT = new HashSet<YL_DATASOURCE_IMPORT>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string CODE { get; set; }
        public string TYPE { get; set; }
        public string REPLACE_STR { get; set; }
        public string RUN_DATA { get; set; }
        public Nullable<int> DB_SERVER_ID { get; set; }
        public string REMARK { get; set; }
        public string STATUS { get; set; }
    
        public virtual ICollection<YL_DATASOURCE_FILED> YL_DATASOURCE_FILED { get; set; }
        public virtual ICollection<YL_DATASOURCE_WHERE> YL_DATASOURCE_WHERE { get; set; }
        public virtual ICollection<YL_DATASOURCE_IMPORT> YL_DATASOURCE_IMPORT { get; set; }
    }
}
