//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_DISTRICT
    {
        public YL_DISTRICT()
        {
            this.YL_BBS = new HashSet<YL_BBS>();
            this.YL_DISTRICT1 = new HashSet<YL_DISTRICT>();
            this.YL_DISTRICT_REGION = new HashSet<YL_DISTRICT_REGION>();
            this.YL_USER = new HashSet<YL_USER>();
            this.YL_USER1 = new HashSet<YL_USER>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public string NAME { get; set; }
        public string CODE { get; set; }
        public short IN_USE { get; set; }
        public int LEVEL_ID { get; set; }
        public string ID_PATH { get; set; }
        public string REGION { get; set; }
    
        public virtual ICollection<YL_BBS> YL_BBS { get; set; }
        public virtual ICollection<YL_DISTRICT> YL_DISTRICT1 { get; set; }
        public virtual YL_DISTRICT YL_DISTRICT2 { get; set; }
        public virtual ICollection<YL_DISTRICT_REGION> YL_DISTRICT_REGION { get; set; }
        public virtual ICollection<YL_USER> YL_USER { get; set; }
        public virtual ICollection<YL_USER> YL_USER1 { get; set; }
    }
}
