//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_DATASOURCE_IMPORT
    {
        public int ID { get; set; }
        public int DATASOURCE_ID { get; set; }
        public Nullable<System.DateTime> ADD_TIME { get; set; }
        public Nullable<int> SUCC_ROW_NUM { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string TABLE_NAME { get; set; }
        public Nullable<int> FILE_ID { get; set; }
    
        public virtual YL_DATASOURCE YL_DATASOURCE { get; set; }
    }
}
