//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_DB_SERVER_TYPE
    {
        public YL_DB_SERVER_TYPE()
        {
            this.YL_DB_SERVER = new HashSet<YL_DB_SERVER>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string REMARK { get; set; }
    
        public virtual ICollection<YL_DB_SERVER> YL_DB_SERVER { get; set; }
    }
}
