//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_EXPORT_LOG
    {
        public int ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string LOGIN_NAME { get; set; }
        public string NAME { get; set; }
        public string SQL { get; set; }
        public Nullable<System.DateTime> EXPORT_TIME { get; set; }
        public string REMARK { get; set; }
    }
}
