//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_FLOW_FLOWNODE_FLOW
    {
        public YL_FLOW_FLOWNODE_FLOW()
        {
            this.YL_ROLE = new HashSet<YL_ROLE>();
        }
    
        public int ID { get; set; }
        public int FLOW_ID { get; set; }
        public int FROM_FLOWNODE_ID { get; set; }
        public int TO_FLOWNODE_ID { get; set; }
        public short HANDLE { get; set; }
        public short ASSIGNER { get; set; }
        public string STATUS { get; set; }
        public string REMARK { get; set; }
        public int EXPIRE_HOUR { get; set; }
    
        public virtual YL_FLOW YL_FLOW { get; set; }
        public virtual YL_FLOW_FLOWNODE YL_FLOW_FLOWNODE { get; set; }
        public virtual ICollection<YL_ROLE> YL_ROLE { get; set; }
    }
}
