//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_FLOW_FLOWNODE
    {
        public YL_FLOW_FLOWNODE()
        {
            this.YL_FLOW_FLOWNODE_FLOW = new HashSet<YL_FLOW_FLOWNODE_FLOW>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string HANDLE_URL { get; set; }
        public string SHOW_URL { get; set; }
    
        public virtual ICollection<YL_FLOW_FLOWNODE_FLOW> YL_FLOW_FLOWNODE_FLOW { get; set; }
    }
}
