//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_FUNCTION
    {
        public YL_FUNCTION()
        {
            this.YL_ROLE = new HashSet<YL_ROLE>();
        }
    
        public int ID { get; set; }
        public string REMARK { get; set; }
        public string FULL_NAME { get; set; }
        public string NAMESPACE { get; set; }
        public string CLASS_NAME { get; set; }
        public string METHOD_NAME { get; set; }
        public string DLL_NAME { get; set; }
        public string XML_NOTE { get; set; }
    
        public virtual ICollection<YL_ROLE> YL_ROLE { get; set; }
    }
}
