//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_GARAGE
    {
        public YL_GARAGE()
        {
            this.YL_ORDER_RESCUE = new HashSet<YL_ORDER_RESCUE>();
            this.YL_ORDER_RESCUE_SEND = new HashSet<YL_ORDER_RESCUE_SEND>();
            this.YL_USER = new HashSet<YL_USER>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string LANG { get; set; }
        public string LAT { get; set; }
        public string PHONE { get; set; }
        public Nullable<int> PIC_ID { get; set; }
        public string REMARK { get; set; }
    
        public virtual ICollection<YL_ORDER_RESCUE> YL_ORDER_RESCUE { get; set; }
        public virtual ICollection<YL_ORDER_RESCUE_SEND> YL_ORDER_RESCUE_SEND { get; set; }
        public virtual ICollection<YL_USER> YL_USER { get; set; }
    }
}
