//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_INSURER
    {
        public YL_INSURER()
        {
            this.YL_ORDER_INSURE_PRODUCT = new HashSet<YL_ORDER_INSURE_PRODUCT>();
            this.YL_ORDER_INSURE = new HashSet<YL_ORDER_INSURE>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> PIC_ID { get; set; }
    
        public virtual ICollection<YL_ORDER_INSURE_PRODUCT> YL_ORDER_INSURE_PRODUCT { get; set; }
        public virtual ICollection<YL_ORDER_INSURE> YL_ORDER_INSURE { get; set; }
    }
}
