//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_INSURER_PRODUCT
    {
        public YL_INSURER_PRODUCT()
        {
            this.YL_INSURER_PRODUCT1 = new HashSet<YL_INSURER_PRODUCT>();
            this.YL_ORDER_INSURE_PRODUCT = new HashSet<YL_ORDER_INSURE_PRODUCT>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> IS_MUST { get; set; }
        public string ALL_ITEM { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public Nullable<decimal> IS_ALL { get; set; }
        public Nullable<int> IS_MAIN { get; set; }
        public string DEFAULT_VAL { get; set; }
    
        public virtual ICollection<YL_INSURER_PRODUCT> YL_INSURER_PRODUCT1 { get; set; }
        public virtual YL_INSURER_PRODUCT YL_INSURER_PRODUCT2 { get; set; }
        public virtual ICollection<YL_ORDER_INSURE_PRODUCT> YL_ORDER_INSURE_PRODUCT { get; set; }
    }
}
