//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_LOGIN
    {
        public YL_LOGIN()
        {
            this.YL_OAUTH = new HashSet<YL_OAUTH>();
        }
    
        public int ID { get; set; }
        public string LOGIN_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string PHONE_NO { get; set; }
        public string EMAIL_ADDR { get; set; }
        public string VERIFY_CODE { get; set; }
        public Nullable<System.DateTime> VERIFY_TIME { get; set; }
        public Nullable<short> IS_LOCKED { get; set; }
        public Nullable<System.DateTime> PASS_UPDATE_DATE { get; set; }
        public string LOCKED_REASON { get; set; }
        public string REGION { get; set; }
        public Nullable<decimal> FAIL_COUNT { get; set; }
    
        public virtual ICollection<YL_OAUTH> YL_OAUTH { get; set; }
    }
}
