//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_MESSAGE_TYPE
    {
        public YL_MESSAGE_TYPE()
        {
            this.YL_BBS = new HashSet<YL_BBS>();
            this.YL_MESSAGE = new HashSet<YL_MESSAGE>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string TABLE_NAME { get; set; }
        public Nullable<short> IS_USE { get; set; }
        public string REMARK { get; set; }
    
        public virtual ICollection<YL_BBS> YL_BBS { get; set; }
        public virtual ICollection<YL_MESSAGE> YL_MESSAGE { get; set; }
    }
}
