//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_MODULE
    {
        public YL_MODULE()
        {
            this.YL_MODULE1 = new HashSet<YL_MODULE>();
            this.YL_ROLE = new HashSet<YL_ROLE>();
            this.YL_USER = new HashSet<YL_USER>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public string NAME { get; set; }
        public string LOCATION { get; set; }
        public string CODE { get; set; }
        public short IS_DEBUG { get; set; }
        public short IS_HIDE { get; set; }
        public short SHOW_ORDER { get; set; }
        public string DESCRIPTION { get; set; }
        public string IMAGE_URL { get; set; }
        public string DESKTOP_ROLE { get; set; }
        public Nullable<int> W { get; set; }
        public Nullable<int> H { get; set; }
    
        public virtual ICollection<YL_MODULE> YL_MODULE1 { get; set; }
        public virtual YL_MODULE YL_MODULE2 { get; set; }
        public virtual ICollection<YL_ROLE> YL_ROLE { get; set; }
        public virtual ICollection<YL_USER> YL_USER { get; set; }
    }
}
