//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_ORDER_RESCUE_SEND
    {
        public int GARAGE_ID { get; set; }
        public int ORDER_ID { get; set; }
        public int INDEX_NO { get; set; }
        public System.DateTime ADD_TIME { get; set; }
        public Nullable<System.DateTime> ACCEPT_TIME { get; set; }
        public Nullable<int> USER_ID { get; set; }
    
        public virtual YL_GARAGE YL_GARAGE { get; set; }
        public virtual YL_ORDER_RESCUE YL_ORDER_RESCUE { get; set; }
    }
}
