//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_ORDER_INSURE
    {
        public YL_ORDER_INSURE()
        {
            this.YL_ORDER_INSURE_PRODUCT = new HashSet<YL_ORDER_INSURE_PRODUCT>();
        }
    
        public int ID { get; set; }
        public Nullable<int> INSURER_ID { get; set; }
        public string PURCHASE_WAY { get; set; }
        public Nullable<System.DateTime> DATE_START { get; set; }
        public Nullable<System.DateTime> DATE_END { get; set; }
        public Nullable<short> IS_TRANSFER { get; set; }
        public string CAR_USERNAME { get; set; }
        public string ID_NO { get; set; }
        public string CAR_OWNER { get; set; }
        public string INSURED_NAME { get; set; }
        public string PROPOSER_NAME { get; set; }
        public string DELIVERY { get; set; }
        public Nullable<int> ID_NO_PIC_ID { get; set; }
        public Nullable<int> ID_NO_PIC_ID1 { get; set; }
        public Nullable<int> DRIVING_PIC_ID { get; set; }
        public Nullable<int> DRIVING_PIC_ID1 { get; set; }
        public Nullable<int> DRIVER_PIC_ID { get; set; }
        public Nullable<int> DRIVER_PIC_ID1 { get; set; }
        public Nullable<int> RECOGNIZEE_PIC_ID { get; set; }
        public Nullable<int> RECOGNIZEE_PIC_ID1 { get; set; }
        public string INS_NAME { get; set; }
        public string BUY_USERNAME { get; set; }
        public string MAKE_ORDER_USERNAME { get; set; }
        public string BUSINESS_NATURE { get; set; }
        public string CAR_TYPE { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string BUSINE_USER { get; set; }
        public Nullable<decimal> COST_RATIO { get; set; }
        public Nullable<decimal> SUCC_FEE { get; set; }
        public string CHANNEL_CODE { get; set; }
        public string BE_GROUP { get; set; }
        public string MAKE_GROUP { get; set; }
        public string OPERATOR_USER { get; set; }
        public Nullable<decimal> ALL_COST { get; set; }
        public Nullable<decimal> FACT_COST { get; set; }
        public Nullable<decimal> MEET_COST { get; set; }
        public Nullable<decimal> SETTLE_RATIO { get; set; }
        public Nullable<decimal> WAIT_MEET_COST { get; set; }
        public Nullable<System.DateTime> SETTLE_TIME { get; set; }
        public string DO_PEOPLE { get; set; }
    
        public virtual YL_INSURER YL_INSURER { get; set; }
        public virtual YL_ORDER YL_ORDER { get; set; }
        public virtual ICollection<YL_ORDER_INSURE_PRODUCT> YL_ORDER_INSURE_PRODUCT { get; set; }
    }
}
