//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_ORDER_FLOW
    {
        public string ORDER_FLOW_NO { get; set; }
        public string OUT_TRADE_NO { get; set; }
        public Nullable<int> ORDER_ID { get; set; }
        public Nullable<int> LEVEL_ID { get; set; }
        public string SELLER_ID { get; set; }
        public Nullable<decimal> COST { get; set; }
        public string SUBJECT { get; set; }
        public string BODY { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> STATUS_TIME { get; set; }
        public Nullable<int> BEGIN_USER_ID { get; set; }
        public Nullable<System.DateTime> BEGIN_TIME { get; set; }
    
        public virtual YL_ORDER YL_ORDER { get; set; }
    }
}
