//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_OAUTH
    {
        public YL_OAUTH()
        {
            this.YL_LOGIN = new HashSet<YL_LOGIN>();
        }
    
        public int KEY { get; set; }
        public string NAME { get; set; }
        public string REG_URL { get; set; }
        public string LOGIN_URL { get; set; }
        public string REMARK { get; set; }
    
        public virtual ICollection<YL_LOGIN> YL_LOGIN { get; set; }
    }
}
