//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_QUESTION_TYPE
    {
        public YL_QUESTION_TYPE()
        {
            this.YL_QUESTION = new HashSet<YL_QUESTION>();
        }
    
        public string QUESTION_TYPE { get; set; }
        public Nullable<int> ORDER_INDEX { get; set; }
        public string REMARK { get; set; }
        public string IN_USE { get; set; }
        public short IS_OBJECTIVE { get; set; }
    
        public virtual ICollection<YL_QUESTION> YL_QUESTION { get; set; }
    }
}
