//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_QUESTION
    {
        public int ID { get; set; }
        public string QUESTION_TYPE { get; set; }
        public string TITLE { get; set; }
        public string NOTE { get; set; }
        public string CONTENT { get; set; }
        public string ANSWER { get; set; }
        public string KEY_WORD { get; set; }
        public string ANALYSIS { get; set; }
        public string STATUS { get; set; }
        public System.DateTime STATUS_TIME { get; set; }
        public Nullable<int> SCORE { get; set; }
    
        public virtual YL_QUESTION_TYPE YL_QUESTION_TYPE { get; set; }
    }
}
