//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_ROLE
    {
        public YL_ROLE()
        {
            this.YL_ROLE_CONFIG = new HashSet<YL_ROLE_CONFIG>();
            this.YL_ROLE_QUERY_AUTHORITY = new HashSet<YL_ROLE_QUERY_AUTHORITY>();
            this.YL_BULLETIN = new HashSet<YL_BULLETIN>();
            this.YL_FLOW_FLOWNODE_FLOW = new HashSet<YL_FLOW_FLOWNODE_FLOW>();
            this.YL_FUNCTION = new HashSet<YL_FUNCTION>();
            this.YL_MODULE = new HashSet<YL_MODULE>();
            this.YL_USER = new HashSet<YL_USER>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> TYPE { get; set; }
    
        public virtual ICollection<YL_ROLE_CONFIG> YL_ROLE_CONFIG { get; set; }
        public virtual ICollection<YL_ROLE_QUERY_AUTHORITY> YL_ROLE_QUERY_AUTHORITY { get; set; }
        public virtual ICollection<YL_BULLETIN> YL_BULLETIN { get; set; }
        public virtual ICollection<YL_FLOW_FLOWNODE_FLOW> YL_FLOW_FLOWNODE_FLOW { get; set; }
        public virtual ICollection<YL_FUNCTION> YL_FUNCTION { get; set; }
        public virtual ICollection<YL_MODULE> YL_MODULE { get; set; }
        public virtual ICollection<YL_USER> YL_USER { get; set; }
    }
}
