//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_SCRIPT_GROUP_LIST
    {
        public int SCRIPT_ID { get; set; }
        public int GROUP_ID { get; set; }
        public int ORDER_INDEX { get; set; }
    
        public virtual YL_SCRIPT YL_SCRIPT { get; set; }
    }
}
