//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_SCRIPT
    {
        public YL_SCRIPT()
        {
            this.YL_SCRIPT_GROUP_LIST = new HashSet<YL_SCRIPT_GROUP_LIST>();
            this.YL_SCRIPT_TASK = new HashSet<YL_SCRIPT_TASK>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string BODY_TEXT { get; set; }
        public string BODY_HASH { get; set; }
        public string RUN_WHEN { get; set; }
        public string RUN_ARGS { get; set; }
        public string RUN_DATA { get; set; }
        public string STATUS { get; set; }
        public string DISABLE_REASON { get; set; }
        public string SERVICE_FLAG { get; set; }
        public string REGION { get; set; }
        public short IS_GROUP { get; set; }
    
        public virtual ICollection<YL_SCRIPT_GROUP_LIST> YL_SCRIPT_GROUP_LIST { get; set; }
        public virtual ICollection<YL_SCRIPT_TASK> YL_SCRIPT_TASK { get; set; }
    }
}
