//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_SCRIPT_TASK
    {
        public YL_SCRIPT_TASK()
        {
            this.YL_SCRIPT_TASK_LOG = new HashSet<YL_SCRIPT_TASK_LOG>();
        }
    
        public int ID { get; set; }
        public int SCRIPT_ID { get; set; }
        public string BODY_TEXT { get; set; }
        public string BODY_HASH { get; set; }
        public string RUN_STATE { get; set; }
        public string RUN_WHEN { get; set; }
        public string RUN_ARGS { get; set; }
        public string RUN_DATA { get; set; }
        public Nullable<short> LOG_TYPE { get; set; }
        public string DSL_TYPE { get; set; }
        public string RETURN_CODE { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public Nullable<System.DateTime> DISABLE_DATE { get; set; }
        public string DISABLE_REASON { get; set; }
        public string SERVICE_FLAG { get; set; }
        public string REGION { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
    
        public virtual YL_SCRIPT YL_SCRIPT { get; set; }
        public virtual ICollection<YL_SCRIPT_TASK_LOG> YL_SCRIPT_TASK_LOG { get; set; }
    }
}
