//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_TASK_FLOW
    {
        public YL_TASK_FLOW()
        {
            this.YL_TASK_FLOW_HANDLE = new HashSet<YL_TASK_FLOW_HANDLE>();
            this.YL_TASK_FLOW_HANDLE_USER = new HashSet<YL_TASK_FLOW_HANDLE_USER>();
            this.YL_TASK_FLOW1 = new HashSet<YL_TASK_FLOW>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public int TASK_ID { get; set; }
        public Nullable<int> LEVEL_ID { get; set; }
        public Nullable<int> FLOWNODE_ID { get; set; }
        public Nullable<int> EQUAL_ID { get; set; }
        public int IS_HANDLE { get; set; }
        public string NAME { get; set; }
        public string HANDLE_URL { get; set; }
        public string SHOW_URL { get; set; }
        public Nullable<System.DateTime> EXPIRE_TIME { get; set; }
        public System.DateTime START_TIME { get; set; }
        public string DEAL_STATUS { get; set; }
        public string ROLE_ID_STR { get; set; }
        public Nullable<int> HANDLE_USER_ID { get; set; }
        public Nullable<System.DateTime> DEAL_TIME { get; set; }
        public Nullable<System.DateTime> ACCEPT_TIME { get; set; }
    
        public virtual YL_TASK YL_TASK { get; set; }
        public virtual ICollection<YL_TASK_FLOW_HANDLE> YL_TASK_FLOW_HANDLE { get; set; }
        public virtual ICollection<YL_TASK_FLOW_HANDLE_USER> YL_TASK_FLOW_HANDLE_USER { get; set; }
        public virtual ICollection<YL_TASK_FLOW> YL_TASK_FLOW1 { get; set; }
        public virtual YL_TASK_FLOW YL_TASK_FLOW2 { get; set; }
    }
}
