//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_TASK
    {
        public YL_TASK()
        {
            this.YL_TASK_FLOW = new HashSet<YL_TASK_FLOW>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FLOW_ID { get; set; }
        public string TASK_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public string CREATE_USER_NAME { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> STATUS_TIME { get; set; }
        public string REMARK { get; set; }
        public string REGION { get; set; }
        public string KEY { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public Nullable<System.DateTime> DEAL_TIME { get; set; }
        public string ROLE_ID_STR { get; set; }
    
        public virtual YL_FLOW YL_FLOW { get; set; }
        public virtual ICollection<YL_TASK_FLOW> YL_TASK_FLOW { get; set; }
    }
}
