//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_TEAM
    {
        public YL_TEAM()
        {
            this.YL_SALESMAN = new HashSet<YL_SALESMAN>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string REQUEST_CODE { get; set; }
        public string REMARK { get; set; }
        public int ADD_USER_ID { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string LEAD_ID_STR { get; set; }
    
        public virtual ICollection<YL_SALESMAN> YL_SALESMAN { get; set; }
    }
}
