//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_USER_CARD
    {
        public YL_USER_CARD()
        {
            this.YL_USER_WITHDRAW = new HashSet<YL_USER_WITHDRAW>();
        }
    
        public int ID { get; set; }
        public int USER_ID { get; set; }
        public string BANK_NAME { get; set; }
        public string USER_NAME { get; set; }
        public string CARD_NUMBER { get; set; }
        public string STATUS { get; set; }
        public System.DateTime STATUS_TIME { get; set; }
    
        public virtual YL_USER YL_USER { get; set; }
        public virtual ICollection<YL_USER_WITHDRAW> YL_USER_WITHDRAW { get; set; }
    }
}
