//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class YL_WEIXIN_USER
    {
        public string OPENID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string NICKNAME { get; set; }
        public Nullable<decimal> SUBSCRIBE { get; set; }
        public Nullable<decimal> SEX { get; set; }
        public string CITY { get; set; }
        public string COUNTRY { get; set; }
        public string PROVINCE { get; set; }
        public string LANGUAGE { get; set; }
        public string HEADIMGURL { get; set; }
        public Nullable<System.DateTime> TAKE_TIME { get; set; }
        public Nullable<System.DateTime> EXIT_TIME { get; set; }
        public string SCENE_STR { get; set; }
    }
}
